// leave off @2x/@3x
const MonsterImages = {
  Anjanath: require('../Images/monsters/MHW-Anjanath_Icon.png'),
  Apceros: require('../Images/monsters/MHW-Apceros_Icon.png'),
  Aptonoth: require('../Images/monsters/MHW-Aptonoth_Icon.png'),
  AzureRathalos: require('../Images/monsters/MHW-Azure_Rathalos_Icon.png'),
  Barnos: require('../Images/monsters/MHW-Barnos_Icon.png'),
  Barroth: require('../Images/monsters/MHW-Barroth_Icon.png'),
  Bazelgeuse: require('../Images/monsters/MHW-Bazelgeuse_Icon.png'),
  BlackDiablos: require('../Images/monsters/MHW-Black_Diablos_Icon.png'),
  Diablos: require('../Images/monsters/MHW-Diablos_Icon.png'),
  Dodogama: require('../Images/monsters/MHW-Dodogama_Icon.png'),
  Gajau: require('../Images/monsters/MHW-Gajau_Icon.png'),
  Gastodon: require('../Images/monsters/MHW-Gastodon_Icon.png'),
  Girros: require('../Images/monsters/MHW-Girros_Icon.png'),
  GreatGirros: require('../Images/monsters/MHW-Great_Girros_Icon.png'),
  GreatJagras: require('../Images/monsters/MHW-Great_Jagras_Icon.png'),
  Hornetaur: require('../Images/monsters/MHW-Hornetaur_Icon.png'),
  Jagras: require('../Images/monsters/MHW-Jagras_Icon.png'),
  Jyuratodus: require('../Images/monsters/MHW-Jyuratodus_Icon.png'),
  Kelbi: require('../Images/monsters/MHW-Kelbi_Icon.png'),
  Kestodon: require('../Images/monsters/MHW-Kestodon_Icon.png'),
  Kirin: require('../Images/monsters/MHW-Kirin_Icon.png'),
  KuluYaKu: require('../Images/monsters/MHW-Kulu-Ya-Ku_Icon.png'),
  KushalaDaora: require('../Images/monsters/MHW-Kushala_Daora_Icon.png'),
  Lavasioth: require('../Images/monsters/MHW-Lavasioth_Icon.png'),
  Legiana: require('../Images/monsters/MHW-Legiana_Icon.png'),
  Mernos: require('../Images/monsters/MHW-Mernos_Icon.png'),
  Mosswine: require('../Images/monsters/MHW-Mosswine_Icon.png'),
  Nergigante: require('../Images/monsters/MHW-Nergigante_Icon.png'),
  Noios: require('../Images/monsters/MHW-Noios_Icon.png'),
  Odogaron: require('../Images/monsters/MHW-Odogaron_Icon.png'),
  Paolumu: require('../Images/monsters/MHW-Paolumu_Icon.png'),
  PinkRathian: require('../Images/monsters/MHW-Pink_Rathian_Icon.png'),
  PukeiPukei: require('../Images/monsters/MHW-Pukei-Pukei_Icon.png'),
  Radobaan: require('../Images/monsters/MHW-Radobaan_Icon.png'),
  Raphinos: require('../Images/monsters/MHW-Raphinos_Icon.png'),
  Rathalos: require('../Images/monsters/MHW-Rathalos_Icon.png'),
  Rathian: require('../Images/monsters/MHW-Rathian_Icon.png'),
  Shamos: require('../Images/monsters/MHW-Shamos_Icon.png'),
  Teostra: require('../Images/monsters/MHW-Teostra_Icon.png'),
  TobiKadachi: require('../Images/monsters/MHW-Tobi-Kadachi_Icon.png'),
  TzitziYaKu: require('../Images/monsters/MHW-Tzitzi-Ya-Ku_Icon.png'),
  Uragaan: require('../Images/monsters/MHW-Uragaan_Icon.png'),
  VaalHazak: require('../Images/monsters/MHW-Vaal_Hazak_Icon.png'),
  Vespoid: require('../Images/monsters/MHW-Vespoid_Icon.png'),
  Xenojiiva: require('../Images/monsters/MHW-Xenojiiva_Icon.png'),
  ZorahMagdaros: require('../Images/monsters/MHW-Zorah_Magdaros_Icon.png'),
  Unknown: require('../Images/monsters/MHW-Unknown_Monster_Icon.png'),
}

export default MonsterImages
